---
title: "garbage markdown"
author: "George"
date: "4/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## R Markdown
```{r}
library(tidyverse)
library(keras)
library(tensorflow)
library(reticulate)
```

```{r}

library(tidyverse)
library(keras)
library(tensorflow)
library(reticulate)
install_tensorflow()
```

```{r}
install.packages("C:/Users/adarsh/Downloads/cli/cli_3.2.0.tar", repos=NULL, type="source")
```


```{r}
install.packages("forecast",
                 repos = c("http://rstudio.org/_packages",
                           "http://cran.rstudio.com"))
```
```{r}

setwd("C:/Users/adarsh/Documents/GitHub/garbageclassification/output")
label_list <- dir("train/")
output_n <- length(label_list)
save(label_list, file="label_list.R") #till george
```

```{r}
width <- 224
height<- 224
target_size <- c(width, height)
rgb <- 3 #color channels
```

```{r}

path_train <- "/train/"
train_data_gen <- image_data_generator(rescale = 1/255, 
  validation_split = .2)
```


```{r}

```

